name       : libtcod
version    : 1.5.1
release    : 4
source     :
    - https://github.com/libtcod/libtcod/archive/refs/tags/1.5.1.tar.gz : f4c052eec562a7e38eb6ebfc14c85c94033a6a3bd8548be31589fb4161b6c400
license    : BSD-3-Clause
component  : programming
summary    : Roguelike graphics/utility library
description: |
    libtcod is a free, fast, portable and uncomplicated API for roguelike developers providing an advanced true color console, input, and lots of other utilities frequently used in roguelikes.
libsplit   : no
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig(glu)
    - pkgconfig(x11)
build      : |
    %make -j1 -f makefiles/makefile-linux64 clean release TEMP=$workdir/tmp
install    : |
    install -d $installdir%libdir%
    install -d $installdir/usr/include/libtcod
    install -Dm00644 libtcod{,gui,xx}.so $installdir/%libdir%
    install -Dm00644 include/*.h* $installdir/usr/include/libtcod
