name       : libtcod
version    : 1.5.1
release    : 2
source     :
    - https://bitbucket.org/libtcod/libtcod/downloads/libtcod-1.5.1-linux64.tar.gz : 6bd49c714fc1bf4e6a87bfd986f17138ef892765ef04fd0164dbc0c7db82f236
license    : BSD-3-Clause
component  : programming
summary    : Roguelike graphics/utility library
description: |
    libtcod is a free, fast, portable and uncomplicated API for roguelike developers providing an advanced true color console, input, and lots of other utilities frequently used in roguelikes.
libsplit   : no
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig(glu)
build      : |
    %make -j1 -f makefiles/makefile-linux64 clean release TEMP=$workdir/tmp
install    : |
    install -d $installdir%libdir%
    install -d $installdir/usr/include/libtcod
    install -Dm00644 libtcod{,gui,xx}.so $installdir/%libdir%
    install -Dm00644 include/*.h* $installdir/usr/include/libtcod
